spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduated_design_database
    username: root
    password: 123
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 300MB
      max-request-size: 300MB
  mail:
    default-encoding: UTF-8
    #发送邮件的账户
    # 授权码（获取方式前文已描述）
    username: 1481167030@qq.com
    password: qqdxdkqxyxrvhhei
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mail:
  from: 1481167030@qq.com
  activeSubject: 账户激活
  forgetCodeSubject: 忘记密码
  activeContent:
  preActiveContent: <h3>请点击下面的链接激活你的账号</h3><br><a href="http://localhost:8080/account/user/active/
  subActiveContent: /">点击这里激活你的账户</a>
  forgetCodeContent: 验证码：

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
file:
  upload:
    paths: classpath:static/image/headportrait,classpath:static/image/emoji,classpath:static/image/thumbnail,classpath:static/image/face

opencv:
  xml: F:/opencv/opencv/sources/data/haarcascades/haarcascade_frontalface_alt.xml
